# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0dfjfmf7nw57vz759zhpd8wj1wd94cm946rp4ybm76b3z4p3kg1y";
    aarch64-linux = "0zv04mn61zm8b7sghmvg57sq7f951pl7nblr3pd7fq4gavgk2a2s";
    x86_64-darwin = "1g1jg4n0svb3mx4sryw4j7b0jqzy0blkigvnjamw3p66wwp0y1p7";
    aarch64-darwin = "1wlx8gcs3hh6r7rc04pxplpcyd998794kl2nziwwhxmi0dcmv1kn";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "tiny-ping-0.7.1-x86_64-unknown-linux-gnu";
    aarch64-linux = "tiny-ping-0.7.1-aarch64-unknown-linux-gnu";
    x86_64-darwin = "tiny-ping-0.7.1-x86_64-apple-darwin";
    aarch64-darwin = "tiny-ping-0.7.1-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tiny-ping";
  version = "0.7.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tiny-ping $out/bin/tiny-ping
  '';

  meta = {
    description = "Small Asynchronous ICMP library and CLI";
    homepage = "https://github.com/Fierthraix/tiny-ping";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
