# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "16szplqw1818r77b6mpqppwbb8d69wbr5ic5plzl80ii8h5d5k10";
    aarch64-linux = "18c5sir4gdqrqh1c5z4irjyk4hpyfcr3c379g1fd0m3xfd3f5azc";
    x86_64-darwin = "12xlyz7kg8kh7zcns8qq71x7wiw37jfciyq41cb1avxbiyy0cazd";
    aarch64-darwin = "0qnayhnhydig7h6z1xmrxxjgwf6x18hfvndq1rjfnh4rw1mll7ii";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/tiny-ping/releases/download/v0.7.1/tiny-ping-0.7.1-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "tiny-ping-0.7.1-x86_64-unknown-linux-gnu";
    aarch64-linux = "tiny-ping-0.7.1-aarch64-unknown-linux-gnu";
    x86_64-darwin = "tiny-ping-0.7.1-x86_64-apple-darwin";
    aarch64-darwin = "tiny-ping-0.7.1-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tiny-ping";
  version = "0.7.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tiny-ping $out/bin/tiny-ping
  '';

  meta = {
    description = "Small Asynchronous ICMP library and CLI";
    homepage = "https://github.com/Fierthraix/tiny-ping";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
