# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0snzdk42yz046valpsvkgih8pjwi7pvbyyvsdj80piibb5pv737a";
    aarch64-linux = "0y5n5cs8q74m0hz0v64hzanxyycrwzjcqsq0xj05616fqyk2gszw";
    x86_64-darwin = "01h44q5wr045wlm42j37p9qz1gl1kcpfqswc76b7ifpw16nbkmv2";
    aarch64-darwin = "07i1ma4lpw1p7yqyaskssqhf31slh4vn8fh0m6z5cs3rckhjjq1w";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "klavaro-1.0.5-x86_64-unknown-linux-gnu";
    aarch64-linux = "klavaro-1.0.5-aarch64-unknown-linux-gnu";
    x86_64-darwin = "klavaro-1.0.5-x86_64-apple-darwin";
    aarch64-darwin = "klavaro-1.0.5-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "klavaro";
  version = "1.0.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./klavaro $out/bin/klavaro
  '';

  meta = {
    description = "Print your current xkb_layout in Sway.";
    homepage = "https://github.com/Fierthraix/klavaro";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
