# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1h1901w46r5w64vsrxml02m3nb5jpf5mm9905j5ikxyh9977sfcs";
    aarch64-linux = "1f39ri29klvid6sns14kvslmga44a6i6zs3sdd0jkfd2f0yck27h";
    x86_64-darwin = "1avvj8gvifbl8dyvgg7axcyhzj0g0mxrb9qq79xzq9fs2202hm6l";
    aarch64-darwin = "10vyqj57djlbycx4bqscrdnx9lpl85q9fx094pr0ybw2lppw81zc";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/klavaro/releases/download/v1.0.5/klavaro-1.0.5-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "klavaro-1.0.5-x86_64-unknown-linux-gnu";
    aarch64-linux = "klavaro-1.0.5-aarch64-unknown-linux-gnu";
    x86_64-darwin = "klavaro-1.0.5-x86_64-apple-darwin";
    aarch64-darwin = "klavaro-1.0.5-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "klavaro";
  version = "1.0.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./klavaro $out/bin/klavaro
  '';

  meta = {
    description = "Print your current xkb_layout in Sway.";
    homepage = "https://github.com/Fierthraix/klavaro";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
