# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0s5v4ibjqvlvs703imkjzyngmj707gwni8zh1k9cnhk3g0s21x6b";
    aarch64-linux = "1gfl5vyk3d00bc2dv6ajxpqmy76g5pq3arwhbzawf1zwhysl323a";
    x86_64-darwin = "0r2xd5cral7d8f157q7f8airabs5q94ws5ivvj44bn8iqfsjjy7j";
    aarch64-darwin = "01mvs3zwpj1xvzcgmzkzlb4ww1mgqqq9abhgkxrki3rg8hbrs4b1";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "rimilo-0.2.8-x86_64-unknown-linux-gnu";
    aarch64-linux = "rimilo-0.2.8-aarch64-unknown-linux-gnu";
    x86_64-darwin = "rimilo-0.2.8-x86_64-apple-darwin";
    aarch64-darwin = "rimilo-0.2.8-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rimilo";
  version = "0.2.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./rimilo $out/bin/rimilo
  '';

  meta = {
    description = "Rapida rimvort-serchilo por Esperanto-angla vortaro.";
    homepage = "https://github.com/Fierthraix/rimilo";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
