# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "10r86rspb2awk3z2k3j03n9yw6xxshq6jy5hdhf7khw6gicgym6c";
    aarch64-linux = "1dcsnhlvki6gq3xxdwyvsk31an3164dpccqc4klqvb9l6s2a11is";
    x86_64-darwin = "1gh8wcbk31as1gzqj759lsb5i5dvm6g84v5bhv02s7svmknrwwqi";
    aarch64-darwin = "1wl3adz2k29h7fq4ay31xx6i4zfnfdall20r5xc40mzj9cgshp7m";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/rimilo/releases/download/v0.2.8/rimilo-0.2.8-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "rimilo-0.2.8-x86_64-unknown-linux-gnu";
    aarch64-linux = "rimilo-0.2.8-aarch64-unknown-linux-gnu";
    x86_64-darwin = "rimilo-0.2.8-x86_64-apple-darwin";
    aarch64-darwin = "rimilo-0.2.8-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rimilo";
  version = "0.2.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./rimilo $out/bin/rimilo
  '';

  meta = {
    description = "Rapida rimvort-serchilo por Esperanto-angla vortaro.";
    homepage = "https://github.com/Fierthraix/rimilo";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
