# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0sp6h6lia6ir2dxwbr4i2ah5a1848aw4rbpjxiwn9lqnm03sbzc0";
    aarch64-linux = "14sxqh9aidgcac4fif6h4cyqwd70nfxnfh9xikx0858i68xad1bw";
    x86_64-darwin = "1g7xs8g8cdc0xa7aqyp8dr0lp6mjqpr9bmp9m1l3hnwpcbbf4c26";
    aarch64-darwin = "0nyqqhjaimsfdhzdq08ka2ba61bh63csy0rgrkzigfgp45r01l32";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "sehx-0.1.3-x86_64-unknown-linux-gnu";
    aarch64-linux = "sehx-0.1.3-aarch64-unknown-linux-gnu";
    x86_64-darwin = "sehx-0.1.3-x86_64-apple-darwin";
    aarch64-darwin = "sehx-0.1.3-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "sehx";
  version = "0.1.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./sehx $out/bin/sehx
  '';

  meta = {
    description = "SEnsible HeXadecimal, the ASCII-synergetic little-endian hexadecimal format.";
    homepage = "https://github.com/Fierthraix/sehx-rs";
    license = lib.licenses.lgpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
