# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0czlgr1l00l0alh8jq01viik4k5vvm49m2v852xc5pq915q6dc6j";
    aarch64-linux = "1fc4n4m6nb1x2fdy13zkg5jff8fb37diac39br0kvrsify2yiimh";
    x86_64-darwin = "15mcyw2p158safrrvzxw887c3z2zv851vvr4av4qldphnzhfpji8";
    aarch64-darwin = "1za4ln4jpawyj07aafvflx5vvivnxnir65jqbdzl31mhv0wa387v";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/sehx-rs/releases/download/v0.1.3/sehx-0.1.3-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "sehx-0.1.3-x86_64-unknown-linux-gnu";
    aarch64-linux = "sehx-0.1.3-aarch64-unknown-linux-gnu";
    x86_64-darwin = "sehx-0.1.3-x86_64-apple-darwin";
    aarch64-darwin = "sehx-0.1.3-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "sehx";
  version = "0.1.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./sehx $out/bin/sehx
  '';

  meta = {
    description = "SEnsible HeXadecimal, the ASCII-synergetic little-endian hexadecimal format.";
    homepage = "https://github.com/Fierthraix/sehx-rs";
    license = lib.licenses.lgpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
