# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0kj4g6rf9bhyzwivnr7xbfp7pgi8mq5b5xnmib4w7ljjfqlcm4cg";
    aarch64-linux = "0nwspbq6vffyvjd1mjacrhni09ycgr3sk1b3z5yvpw7vin372z37";
    x86_64-darwin = "0g8k6xzqv1n4svj0kf33digiaswjf814j0n58sncbwy2yfy12n2p";
    aarch64-darwin = "12wk1v08lqqzq30j9cbcbls5z9mv7zdyiwqsyhns8qczykzzfnvx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "rmatrix-2.0.3-x86_64-unknown-linux-gnu";
    aarch64-linux = "rmatrix-2.0.3-aarch64-unknown-linux-gnu";
    x86_64-darwin = "rmatrix-2.0.3-x86_64-apple-darwin";
    aarch64-darwin = "rmatrix-2.0.3-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rmatrix";
  version = "2.0.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./r-matrix $out/bin/r-matrix
  '';

  meta = {
    description = "Rust port of cmatrix.";
    homepage = "https://github.com/Fierthraix/rmatrix";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
