# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0hzjs1k7j0iggfs42fmzy1df5i8l3b3w7dfhmf78x17y276q3rgx";
    aarch64-linux = "0814rvxpmd1wd5dzhcy1my2kssbfkds8b01wh7vid2ydlf2l1kql";
    x86_64-darwin = "0jgca92rxknsm0m59yrr2qph9g4j85nq8jdaiw8c0w66agszbjz2";
    aarch64-darwin = "13n1np3slf67nsii61zqrd8kqfml9r5p9fpvj7a56v8pgy3n4g0l";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/rmatrix/releases/download/v2.0.3/rmatrix-2.0.3-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "rmatrix-2.0.3-x86_64-unknown-linux-gnu";
    aarch64-linux = "rmatrix-2.0.3-aarch64-unknown-linux-gnu";
    x86_64-darwin = "rmatrix-2.0.3-x86_64-apple-darwin";
    aarch64-darwin = "rmatrix-2.0.3-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rmatrix";
  version = "2.0.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./r-matrix $out/bin/r-matrix
  '';

  meta = {
    description = "Rust port of cmatrix.";
    homepage = "https://github.com/Fierthraix/rmatrix";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
