# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0m88rs5h04yhm4xl9py0lpg2id77zx7nyfjlfsjggmd03j8xm56w";
    aarch64-linux = "17c6dgw2d36113yk1fwk1c238yi69c40cnjxxipg7kvnz5jymav3";
    x86_64-darwin = "06alcklxp6prc3zywmicikn15mbk7h5gb939zcb994j8mr6di64f";
    aarch64-darwin = "0pwy0b885802pijqk99mncw1avdcln4lhh49w51zcx2ips4h260s";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "aodv-0.2.2-x86_64-unknown-linux-gnu";
    aarch64-linux = "aodv-0.2.2-aarch64-unknown-linux-gnu";
    x86_64-darwin = "aodv-0.2.2-x86_64-apple-darwin";
    aarch64-darwin = "aodv-0.2.2-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "aodv";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./aodv $out/bin/aodv
  '';

  meta = {
    description = "Userspace AODV control-plane implementation based on RFC 3561";
    homepage = "https://github.com/Fierthraix/aodv-rs";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
