# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1qjksa7y1l0wlmjy4jba52q1k5ks766i6wsxnjzngm9qlirqyxk5";
    aarch64-linux = "19aqp2njpn0if19ldv1prd8a3kkdvzllyg9fpd8433bs5q7j2y4w";
    x86_64-darwin = "10ld8k7kc7y0iq91xgknkcv6cjkn4bnvzpyz73vi649imhxw1cfq";
    aarch64-darwin = "0xa2zj3sk619qnsvhh02m2ywhvilw2v4p1y0lbf9zavm3yjvl7fz";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/aodv-rs/releases/download/v0.2.2/aodv-0.2.2-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "aodv-0.2.2-x86_64-unknown-linux-gnu";
    aarch64-linux = "aodv-0.2.2-aarch64-unknown-linux-gnu";
    x86_64-darwin = "aodv-0.2.2-x86_64-apple-darwin";
    aarch64-darwin = "aodv-0.2.2-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "aodv";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./aodv $out/bin/aodv
  '';

  meta = {
    description = "Userspace AODV control-plane implementation based on RFC 3561";
    homepage = "https://github.com/Fierthraix/aodv-rs";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
