# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1fwrm4kxhrqkzniys8f3v5zargpl7y3lcx3cjp2zdfr7w89ng106";
    aarch64-linux = "14kf6rv5qr24g4zds89jpw6989vbm09vw5qzwgwcs21q3jnqk2aa";
    x86_64-darwin = "1jn72i72v3jfjlpd6sh6s6965k5z2d5xjm5p1h4chsd93avhzdps";
    aarch64-darwin = "062f7s62xxn5kn68jip4sdbyi48kqjmm45v07c0nb875zr47pr7p";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "pingall-2.1.5-x86_64-unknown-linux-gnu";
    aarch64-linux = "pingall-2.1.5-aarch64-unknown-linux-gnu";
    x86_64-darwin = "pingall-2.1.5-x86_64-apple-darwin";
    aarch64-darwin = "pingall-2.1.5-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pingall";
  version = "2.1.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pingall $out/bin/pingall
  '';

  meta = {
    description = "Ping everything you can reach.";
    homepage = "https://github.com/Fierthraix/pingall";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
