# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1z7d7akqj7kbjgqf1bginxgw26s0yjsi34gh8s7d5hc4gy61i8bd";
    aarch64-linux = "0jgcp2r2rkq9gsj7z44959grrhrc3k9y9khrraracarjdg116715";
    x86_64-darwin = "0kvlfhfv9cd3a9p49048jihivm1qv1z6zqm59cf60c3477mw8zng";
    aarch64-darwin = "04giwllpgfyrc1m0z715m3cpr9g6xpi0fvmjrx690wnmg37krp9i";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/pingall/releases/download/v2.1.5/pingall-2.1.5-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "pingall-2.1.5-x86_64-unknown-linux-gnu";
    aarch64-linux = "pingall-2.1.5-aarch64-unknown-linux-gnu";
    x86_64-darwin = "pingall-2.1.5-x86_64-apple-darwin";
    aarch64-darwin = "pingall-2.1.5-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pingall";
  version = "2.1.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pingall $out/bin/pingall
  '';

  meta = {
    description = "Ping everything you can reach.";
    homepage = "https://github.com/Fierthraix/pingall";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
