# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0z84a6i1ypkndkwbirxcdcikp0qjqsbmhxp1zd4yr2gzqjz3b0n3";
    aarch64-linux = "01mcmlvkda1g9fclmq6mb2p1pjbk8g5gh9flh59h5f48bf603729";
    x86_64-darwin = "0v89wpac2kq2wcrxbzvdv708xcski07107adz11m4vag09v3k1qy";
    aarch64-darwin = "0fmq4hq96bb5vkjk2illx5f4m5zx1q7fg5c922b33s1pqixalwa1";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "proverbilo-0.1.9-x86_64-unknown-linux-gnu";
    aarch64-linux = "proverbilo-0.1.9-aarch64-unknown-linux-gnu";
    x86_64-darwin = "proverbilo-0.1.9-x86_64-apple-darwin";
    aarch64-darwin = "proverbilo-0.1.9-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "proverbilo";
  version = "0.1.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./proverbilo $out/bin/proverbilo
  '';

  meta = {
    description = "Programo por montri hazardajn proverbojn en Esperanto.";
    homepage = "https://github.com/Fierthraix/proverbilo";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
