# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "07f2r6l5r2bxq88hb1d31paihbsqndpfilryxm7pxfzqqrxw2vbb";
    aarch64-linux = "0p1rfmkmvhb04pm2xwl9j2jbdns5jl9i87x75pl6971iv3k30dvs";
    x86_64-darwin = "1b9a5b62cgalq01vh4xcfq1i2hz7b9av4nk5zy4mi6dpq47r6mi6";
    aarch64-darwin = "0857hyi283na63ll8g4vdpf1zgn2irhhma0bda8qdik7mx8287lm";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-x86_64-unknown-linux-gnu.tar.gz";
    aarch64-linux = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-aarch64-unknown-linux-gnu.tar.gz";
    x86_64-darwin = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-x86_64-apple-darwin.tar.gz";
    aarch64-darwin = "https://github.com/Fierthraix/proverbilo/releases/download/v0.1.9/proverbilo-0.1.9-aarch64-apple-darwin.tar.gz";
  };
  sourceRootMap = {
    x86_64-linux = "proverbilo-0.1.9-x86_64-unknown-linux-gnu";
    aarch64-linux = "proverbilo-0.1.9-aarch64-unknown-linux-gnu";
    x86_64-darwin = "proverbilo-0.1.9-x86_64-apple-darwin";
    aarch64-darwin = "proverbilo-0.1.9-aarch64-apple-darwin";
  };
in
stdenvNoCC.mkDerivation {
  pname = "proverbilo";
  version = "0.1.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./proverbilo $out/bin/proverbilo
  '';

  meta = {
    description = "Programo por montri hazardajn proverbojn en Esperanto.";
    homepage = "https://github.com/Fierthraix/proverbilo";
    license = lib.licenses.gpl3Plus;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
